### ISSUE TITLE
Numbered lists are not rendered

### ISSUE THREAD

**Issue by ThomasLandauer** [doctrine/doctrine-website-sphinx#143]
Numbered lists aren't displayed nicely, see e.g. http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/working-with-associations.html#persistence-by-reachability-cascade-persist

**Comment by guilliamxavier** [comment]
@mikeSimonson That exact problem has already been fixed on the sibling **doctrine-sphinx-theme** repository with the two PRs https://github.com/doctrine/doctrine-sphinx-theme/pull/3 + https://github.com/doctrine/doctrine-sphinx-theme/pull/7 (complete diff: https://github.com/doctrine/doctrine-sphinx-theme/compare/d9bf324126fedc1c97a4353cfc285a72bf71de68%5E...b0b783d2afaf1925054f53cc62478c2ea546e7e4), but the fixes were never applied to the website (maybe because of https://github.com/doctrine/doctrine-website-sphinx/commit/4638998ae765674b28ecdd1dd324bfe276e922c2)?

**Comment by guilliamxavier** [comment]
@ThomasLandauer Now it seems that the fixes have been applied to the website (somehow).

**Comment by alcaeus** [comment]
AFAIK there's an automatic deployment but I've seen that thing mess up once in a while. Thanks for the update, closing this then!
